builders:
  app_route:
    import: "package:app_route_generator/builder.dart"
    builder_factories: ["appRoute"]
    build_extensions: {".dart": [".app_route.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]