name: app_route
description: Keep track of all your TODOs.
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  meta: ^1.7.0
  equatable: any

dev_dependencies:
  flutter_lints: ^1.0.0